### ISSUE TITLE
Remix build error (backend package)

### ISSUE THREAD

**Issue by mme** [CopilotKit/CopilotKit#327]
**Describe the bug**
There is a build error with the backend package when performing a remix production build.

```
✓ 1136 modules transformed.
x Build failed in 669ms
Error [RollupError]: app/routes/copilotkit.tsx (1:9): "CopilotRuntime" is not exported by "../../../Users/mme/Code/CopilotKit/CopilotKit/packages/backend/dist/index.js", imported by "app/routes/copilotkit.tsx".
file: /private/tmp/test-remix-app/app/routes/copilotkit.tsx:1:9
1: import { CopilotRuntime, OpenAIAdapter } from "@copilotkit/backend";
            ^
2: import type { ActionFunctionArgs } from "@remix-run/node";
    at getRollupError (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at error (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/parseAst.js:390:42)
    at Module.error (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:13855:16)
    at Module.traceVariable (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:14303:29)
    at ModuleScope.findVariable (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:11984:39)
    at FunctionScope.findVariable (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
    at FunctionBodyScope.findVariable (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
    at Identifier.bind (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:6908:40)
    at NewExpression.bind (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:4775:23)
    at VariableDeclarator.bind (file:///private/tmp/test-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:4775:23) {
  binding: 'CopilotRuntime',
  code: 'MISSING_EXPORT',
  exporter: '/Users/mme/Code/CopilotKit/CopilotKit/packages/backend/dist/index.js',
  id: '/private/tmp/test-remix-app/app/routes/copilotkit.tsx',
  url: 'https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module',
  pos: 9,
  loc: {
    column: 9,
    file: '/private/tmp/test-remix-app/app/routes/copilotkit.tsx',
    line: 1
  },
  frame: '1: import { CopilotRuntime, OpenAIAdapter } from "@copilotkit/backend";\n' +
    '            ^\n' +
    '2: import type { ActionFunctionArgs } from "@remix-run/node";',
```

**To Reproduce**
1. Create a minimal remix project with an action route that uses `CopilotRuntime` to serve the request
2. `npm run build`

**Expected behavior**
Builds without error

**Comment by MuraraAllan** [comment]
the build error I have so far is from the telemetryClient.
it seems the import from runtime fixed the previous error.

```  303 modules transformed.
x Build failed in 1.06s
node_modules/@copilotkit/shared/dist/chunk-ZUUDJSVP.mjs (6:9): "randomUUID" is not exported by "__vite-browser-external", imported by "node_modules/@copilotkit/shared/dist/chunk-ZUUDJSVP.mjs".
file: /home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/shared/dist/chunk-ZUUDJSVP.mjs:6:9

4:
5: // src/telemetry/telemetry-client.ts
6: import { Analytics } from "@segment/analytics-node";
            ^
7: import { randomUUID } from "crypto";
8: var TelemetryClient = class {

    at getRollupError (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:13967:16)
    at Module.traceVariable (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:14414:29)
    at ModuleScope.findVariable (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:12121:39)
    at ChildScope.findVariable (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at ClassBodyScope.findVariable (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at ChildScope.findVariable (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at ChildScope.findVariable (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at FunctionScope.findVariable (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:7467:38) {
  binding: 'randomUUID',
  code: 'MISSING_EXPORT',
  exporter: '__vite-browser-external',
  id: '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/shared/dist/chunk-ZUUDJSVP.mjs',
  url: 'https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module',
  pos: 155,
  loc: {
    column: 9,
    file: '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/shared/dist/chunk-ZUUDJSVP.mjs',
    line: 6
  },
  frame: '4: \n' +
    '5: // src/telemetry/telemetry-client.ts\n' +
    '6: import { Analytics } from "@segment/analytics-node";\n' +
    '            ^\n' +
    '7: import { randomUUID } from "crypto";\n' +
    '8: var TelemetryClient = class {',
  watchFiles: [
    '/home/zeddd/project/chatbot/my-remix-app/app/entry.client.tsx',
    '/home/zeddd/project/chatbot/my-remix-app/app/routes/runtime_url.tsx',
    '/home/zeddd/project/chatbot/my-remix-app/app/root.tsx',
    '/home/zeddd/project/chatbot/my-remix-app/app/routes/_index.tsx',
    '/home/zeddd/project/chatbot/my-remix-app/app/routes/messages.tsx',
    '/home/zeddd/project/chatbot/my-remix-app/package.json',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/index.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react/jsx-runtime.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react/index.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react-dom/client.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/browser.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/components.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/scroll-restoration.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/server.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/single-fetch.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/index.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react-router-dom/dist/index.js',
    '/home/zeddd/project/chatbot/my-remix-app/app/tailwind.css',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react/cjs/react-jsx-runtime.production.min.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react/cjs/react.production.min.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react-dom/index.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/_virtual/_rollupPluginBabelHelpers.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/routes.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react-router-dom/server.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/cookies.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/formData.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/responses.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/single-fetch.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/server.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/sessions.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/sessions/cookieStorage.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/sessions/memoryStorage.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/upload/memoryUploadHandler.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/upload/errors.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/errorBoundaries.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/dev.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/data.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/markup.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/invariant.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/router/dist/router.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/turbo-stream/dist/turbo-stream.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/app/entry.server.tsx',
    '/home/zeddd/project/chatbot/my-remix-app/tailwind.config.ts',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react-dom/cjs/react-dom.production.min.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/errors.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/fog-of-war.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/react-router/dist/index.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/links.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/routeModules.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/react/dist/esm/fallback.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/warnings.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/cookie/index.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@web3-storage/multipart-parser/esm/src/index.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/errors.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/headers.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/entry.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/mode.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/invariant.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/routeMatching.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/routes.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/serverHandoff.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/deprecations.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/index.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/scheduler/index.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@web3-storage/multipart-parser/esm/src/search.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@web3-storage/multipart-parser/esm/src/utils.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/set-cookie-parser/lib/set-cookie.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/data.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@remix-run/server-runtime/dist/esm/markup.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-YJLRG5U3.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-UQRDVZ2N.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-EFZPSZWO.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-LUGEI4YQ.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-GE7LAL6V.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-VNRDQJXW.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-5JB4B2SV.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-KONDJRB4.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-T6L4EGTD.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-VFDR4MIF.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-YYZNR3CS.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-JD7BAH7U.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-SPCZTZCY.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-TVR5CJ6E.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-5FHSUKQL.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-6U3UH3KO.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-AGGKI26A.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-3NHEWJ4V.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/react-core/dist/chunk-SKC7AJIV.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/scheduler/cjs/scheduler.production.min.js',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/shared/dist/index.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/runtime-client-gql/dist/index.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/shared/dist/chunk-DE5K76I2.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/shared/dist/chunk-MSUB6DGR.mjs',
    '/home/zeddd/project/chatbot/my-remix-app/node_modules/@copilotkit/shared/dist/chunk-IAFBVORQ.mjs',
    '/home/zeddd/project/chatbot/my
    
```
I can fix it by configuring vite into building without the telemetryClient

but sooner I walk in an incompatibility with some polifill I have in the vite.
It works on Dev, so I'm sure it is something from my config and I will come with an example on running and building from remix.


```
},
    _subTypeMap: [Object: null prototype] {},
    _implementationsMap: [Object: null prototype] {
      BaseMessageOutput: [Object],
      BaseResponseStatus: [Object]
    }
  },
  plugins: [
    {
      onSchemaChange: [Function: onSchemaChange],
      onValidate: [Function: onValidate]
    }
  ],
  context: [Function: context]
}
PREFETCH YOGA
Error getting response: TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (/home/zeddd/project/chatbot/my-remix-app/node_modules/web-streams-polyfill/src/lib/validators/readable-stream.ts:5:11)
    at convertReadableWritablePair (/home/zeddd/project/chatbot/my-remix-app/node_modules/web-streams-polyfill/src/lib/validators/readable-writable-pair.ts:15:3)
    at ReadableStream.pipeThrough (/home/zeddd/project/chatbot/my-remix-app/node_modules/web-streams-polyfill/src/lib/readable-stream.ts:223:23)
    at processStream (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/@google/generative-ai/dist/index.mjs:594:39)
    at generateContentStream (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/@google/generative-ai/dist/index.mjs:747:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[19:29:27.757] ERROR: First parameter has member 'readable' that is not a ReadableStream.
    component: "Yoga GraphQL"
    err: {
      "type": "GraphQLError",
      "message": "First parameter has member 'readable' that is not a ReadableStream.",
      "stack":
          TypeError: First parameter has member 'readable' that is not a ReadableStream.
              at assertReadableStream (/home/zeddd/project/chatbot/my-remix-app/node_modules/web-streams-polyfill/src/lib/validators/readable-stream.ts:5:11)
              at convertReadableWritablePair (/home/zeddd/project/chatbot/my-remix-app/node_modules/web-streams-polyfill/src/lib/validators/readable-writable-pair.ts:15:3)
              at ReadableStream.pipeThrough (/home/zeddd/project/chatbot/my-remix-app/node_modules/web-streams-polyfill/src/lib/readable-stream.ts:223:23)
              at processStream (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/@google/generative-ai/dist/index.mjs:594:39)
              at generateContentStream (file:///home/zeddd/project/chatbot/my-remix-app/node_modules/@google/generative-ai/dist/index.mjs:747:12)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
      "path": [
        "generateCopilotResponse"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "extensions": {}
    }
HELLO WORLD RESPONSE Response {
  size: 0,
  [Symbol(Body internals)]: {
    body: ReadableStream {
      _state: 'readable',
      _reader: undefined,
      _storedError: undefined,
      _disturbed: false,
      _readableStreamController: [ReadableStreamDefaultController]
    },
    type: 'text/plain;charset=UTF-8',
    size: 127,
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: undefined,
    status: 200,
    statusText: '',
    headers: {
      'access-control-allow-credentials': 'true',
      'access-control-allow-origin': 'http://localhost:3000',
      'content-type': 'application/graphql-response+json; charset=utf-8',
      vary: 'Origin'
    },
    counter: 0,
    highWaterMark: undefined
  }
}
HELLO WORLD bodY {"errors":[{"message":"Unexpected error.","locations":[{"line":2,"column":3}],"path":["generateCopilotResponse"]}
```

**Comment by jpr5** [comment]
The `@copilotkit/backend` package referenced here has been deprecated. The recommended path forward is [AG-UI](https://docs.ag-ui.com). See the [AG-UI migration guide](https://docs.copilotkit.ai/guides/ag-ui-migration) for the current approach. Closing as outdated.
