### ISSUE TITLE
🐛 Bug: Type errors LangChain Adapter with @copilotkit/runtime 

### ISSUE THREAD

**Issue by useEffects** [CopilotKit/CopilotKit#534]
### ♻️ Reproduction Steps

https://docs.copilotkit.ai/reference/classes/CopilotRuntime/service-adapters/LangChainAdapter

### ✅ Expected Behavior

Show no type errors

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/0dbd0c92-6f00-44d9-8036-db8f8acecc16)

### 𝌚 CopilotKit Version

```shell
├── @copilotkit/backend@0.37.0
├── @copilotkit/runtime@1.1.1
```

### 📄 Logs (Optional)

```shell
Type '({ messages, tools }: ChainFnParameters) => Promise<IterableReadableStream<AIMessageChunk>>' is not assignable to type '(parameters: ChainFnParameters) => Promise<LangChainReturnType>'.
  Type 'Promise<IterableReadableStream<AIMessageChunk>>' is not assignable to type 'Promise<LangChainReturnType>'.
    Type 'IterableReadableStream<AIMessageChunk>' is not assignable to type 'LangChainReturnType'.
      Type 'IterableReadableStream<AIMessageChunk>' is not assignable to type 'LangChainBaseMessageChunkStream'.
        Types of property 'reader' are incompatible.
          Type 'ReadableStreamDefaultReader<AIMessageChunk>' is not assignable to type 'ReadableStreamDefaultReader<BaseMessageChunk>'.
            Type 'AIMessageChunk' is not assignable to type 'BaseMessageChunk'.
              Types of property 'concat' are incompatible.
                Type '(chunk: AIMessageChunk) => AIMessageChunk' is not assignable to type '(chunk: BaseMessageChunk) => BaseMessageChunk'.
                  Types of parameters 'chunk' and 'chunk' are incompatible.
                    Type 'BaseMessageChunk' is missing the following properties from type 'AIMessageChunk': _printableFields, [Symbol.toStringTag]ts(2322)
groq-adapter-675b30c6.d.ts(192, 5): The expected type comes from property 'chainFn' which is declared here on type 'LangChainAdapterOptions'
```
```
Argument of type 'BaseMessage[]' is not assignable to parameter of type 'BaseLanguageModelInput'.
  Type 'BaseMessage[]' is not assignable to type 'BaseMessageLike[]'.
    Type 'BaseMessage' is not assignable to type 'BaseMessageLike'.
      Type 'BaseMessage' is not assignable to type '{ type: "user" | MessageType | "assistant" | "placeholder"; } & BaseMessageFields & Record<string, unknown>'.
        Property 'type' is missing in type 'BaseMessage' but required in type '{ type: "user" | MessageType | "assistant" | "placeholder"; }'.ts(2345)
base.d.ts(157, 5): 'type' is declared here.
```
```
Property 'streamHttpServerResponse' does not exist on type 'CopilotRuntime<[]>'.ts(2339)
```
```

**Comment by useEffects** [comment]
Any update on this?

**Comment by useEffects** [comment]
Works fine with `@langchain/openai` but not with `@langchain/ollama`

**Comment by SonuMondal06** [comment]
I am facing a similar issue for `@langchain/openai`
- Type error in the editor.
- this.chainFn is not a function error in the console on POST request

`import { env } from "@/env.mjs";
import { getResponseForOption } from "@/helpers/ai/api";
import { CopilotRuntime, LangChainAdapter } from "@copilotkit/backend";
import { ChatOpenAI } from "@langchain/openai";

export const runtime = "edge";

export function OPTIONS(req: Request) {
	const response = getResponseForOption(req);
	return response;
}

export const POST = (req: Request, res: Response) => {
	const copilotKit = new CopilotRuntime();

	const model = new ChatOpenAI({
		model: "gpt-4o",
		apiKey: env.API_KEY_OPENAI,
	});

	const serviceAdapter = new LangChainAdapter({
		chainFn: async ({ messages, tools }) => {
			return model.stream(messages, { tools });
		},
	});

	return copilotKit.streamHttpServerResponse(req, res, serviceAdapter);
};
`

<img width="593" alt="Screenshot 2024-09-03 at 5 22 29 PM" src="https://github.com/user-attachments/assets/1245802e-ea8b-43b7-a0e1-d6c3d85b6778">

<img width="252" alt="Screenshot 2024-09-03 at 5 25 53 PM" src="https://github.com/user-attachments/assets/fbdd5836-b5e9-4d16-af03-0113ba0dc569">

`Error getting response: [TypeError: this.chainFn is not a function]
✖ Error [TypeError]: this.chainFn is not a function
    at LangChainAdapter.getResponse (webpack-internal:///./node_modules/@copilotkit/backend/dist/index.js:717:31)
    at CopilotRuntime.getResponse (webpack-internal:///./node_modules/@copilotkit/backend/dist/index.js:551:43)
    at CopilotRuntime.streamHttpServerResponse (webpack-internal:///./node_modules/@copilotkit/backend/dist/index.js:628:33)
    at async eval (webpack-internal:///./node_modules/@sentry/nextjs/build/esm/common/wrapRouteHandlerWithSentry.js:72:36)
`

**Comment by useEffects** [comment]
`import { CopilotRuntime, LangChainAdapter } from "@copilotkit/runtime";` not /backend

**Comment by SonuMondal06** [comment]
Yes, tried that.

While importing from `@copilotkit/runtime` the type error for `streamHttpServerResponse` pops up as well, and
another console issue occurs saying "Can't resolve crypto" that points to `@copilotkit/shared/dist/index.js:149:1`

<img width="669" alt="Screenshot 2024-09-03 at 5 33 29 PM" src="https://github.com/user-attachments/assets/4c841982-374f-4636-b386-adbedd57dd45">

<img width="702" alt="Screenshot 2024-09-03 at 5 34 14 PM" src="https://github.com/user-attachments/assets/dc1a84c7-7b43-4cfa-8ded-f69343fb745f">

**Comment by jpr5** [comment]
LangChainAdapter has been deprecated. The recommended path forward is [AG-UI](https://docs.ag-ui.com). See the [AG-UI migration guide](https://docs.copilotkit.ai/guides/ag-ui-migration) for the current approach. Closing as outdated.
