### ISSUE TITLE
🐛 Bug: Issue with sample application coagents-research-canvas

### ISSUE THREAD

**Issue by salman-khandu** [CopilotKit/CopilotKit#835]
### ♻️ Reproduction Steps

I tried to setup sample application with steps mentioned but i was getting error like
```[17:28:24.255] ERROR: Failed to fetch actions from url
    component: "remote-actions.fetchActionsFromUrl"
    actionDefinition: {
      "url": "http://localhost:8000/copilotkit"
    }
    error: "fetch failed"
[17:28:24.269] ERROR: Agent research_agent not found
    component: "Yoga GraphQL"
    err: {
      "type": "GraphQLError",
      "message": "Agent research_agent not found",
      "stack":
          Error: Agent research_agent not found
              at CopilotRuntime.processAgentRequest (webpack-internal:///(rsc)/./node_modules/.pnpm/@copilotkit+runtime@1.3.6_class-validator@0.14.1_ignore@5.3.2/node_modules/@copilotkit/runtime/dist/index.js:2341:13)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async CopilotResolver.generateCopilotResponse (webpack-internal:///(rsc)/./node_modules/.pnpm/@copilotkit+runtime@1.3.6_class-validator@0.14.1_ignore@5.3.2/node_modules/@copilotkit/runtime/dist/index.js:3606:126)
              at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@envelop+core@5.0.2/node_modules/@envelop/core/cjs/orchestrator.js:386:27)
              at async YogaServer.getResultForParams (webpack-internal:///(rsc)/./node_modules/.pnpm/graphql-yoga@5.7.0_graphql@16.9.0/node_modules/graphql-yoga/cjs/server.js:286:26)
              at async handle (webpack-internal:///(rsc)/./node_modules/.pnpm/graphql-yoga@5.7.0_graphql@16.9.0/node_modules/graphql-yoga/cjs/server.js:365:25)
              at async D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55778
              at async eO.execute (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46527)
              at async eO.handle (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57112)
              at async doRender (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1352:42)
              at async cacheEntry.responseCache.get.routeKind (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1574:28)
              at async DevServer.renderToResponseWithComponentsImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1482:28)
              at async DevServer.renderPageComponent (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1908:24)
              at async DevServer.renderToResponseImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1946:32)
              at async DevServer.pipeImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:921:25)
              at async NextNodeServer.handleCatchallRenderRequest (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\next-server.js:272:17)
              at async DevServer.handleRequestImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:817:17)
              at async D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\dev\next-dev-server.js:339:20
              at async Span.traceAsyncFn (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\trace\trace.js:154:20)
              at async DevServer.handleRequest (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
              at async invokeRender (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-server.js:173:21)
              at async handleRequest (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-server.js:350:24)
              at async requestHandlerImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-server.js:374:13)
              at async Server.requestListener (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\start-server.js:141:13)
      "path": [
        "generateCopilotResponse"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "extensions": {}
    }
 POST /api/copilotkit 200 in 6336ms
```

### ✅ Expected Behavior

It should work 

### ❌ Actual Behavior

Getting error
```
[17:28:24.255] ERROR: Failed to fetch actions from url
    component: "remote-actions.fetchActionsFromUrl"
    actionDefinition: {
      "url": "http://localhost:8000/copilotkit"
    }
    error: "fetch failed"
[17:28:24.269] ERROR: Agent research_agent not found
    component: "Yoga GraphQL"
    err: {
      "type": "GraphQLError",
      "message": "Agent research_agent not found",
      "stack":
          Error: Agent research_agent not found
              at CopilotRuntime.processAgentRequest (webpack-internal:///(rsc)/./node_modules/.pnpm/@copilotkit+runtime@1.3.6_class-validator@0.14.1_ignore@5.3.2/node_modules/@copilotkit/runtime/dist/index.js:2341:13)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async CopilotResolver.generateCopilotResponse (webpack-internal:///(rsc)/./node_modules/.pnpm/@copilotkit+runtime@1.3.6_class-validator@0.14.1_ignore@5.3.2/node_modules/@copilotkit/runtime/dist/index.js:3606:126)
              at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@envelop+core@5.0.2/node_modules/@envelop/core/cjs/orchestrator.js:386:27)
              at async YogaServer.getResultForParams (webpack-internal:///(rsc)/./node_modules/.pnpm/graphql-yoga@5.7.0_graphql@16.9.0/node_modules/graphql-yoga/cjs/server.js:286:26)
              at async handle (webpack-internal:///(rsc)/./node_modules/.pnpm/graphql-yoga@5.7.0_graphql@16.9.0/node_modules/graphql-yoga/cjs/server.js:365:25)
              at async D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55778
              at async eO.execute (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46527)
              at async eO.handle (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57112)
              at async doRender (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1352:42)
              at async cacheEntry.responseCache.get.routeKind (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1574:28)
              at async DevServer.renderToResponseWithComponentsImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1482:28)
              at async DevServer.renderPageComponent (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1908:24)
              at async DevServer.renderToResponseImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:1946:32)
              at async DevServer.pipeImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:921:25)
              at async NextNodeServer.handleCatchallRenderRequest (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\next-server.js:272:17)
              at async DevServer.handleRequestImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:817:17)
              at async D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\dev\next-dev-server.js:339:20
              at async Span.traceAsyncFn (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\trace\trace.js:154:20)
              at async DevServer.handleRequest (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
              at async invokeRender (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-server.js:173:21)
              at async handleRequest (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-server.js:350:24)
              at async requestHandlerImpl (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-server.js:374:13)
              at async Server.requestListener (D:\langgraph\coagents-research-canvas\ui\node_modules\.pnpm\next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\start-server.js:141:13)
      "path": [
        "generateCopilotResponse"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "extensions": {}
    }
 POST /api/copilotkit 200 in 6336ms
```

### 𝌚 CopilotKit Version

```shell
$ npm ls | grep "@copilotkit"
├── @copilotkit/react-core@1.3.6 -> .\node_modules\.pnpm\@copilotkit+react-core@1.3.6_ignore@5.3.2_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\@copilotkit\react-core
├── @copilotkit/react-ui@1.3.6 -> .\node_modules\.pnpm\@copilotkit+react-ui@1.3.6_@types+react@18.3.11_ignore@5.3.2_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\@copilotkit\react-ui
├── @copilotkit/runtime@1.3.6 -> .\node_modules\.pnpm\@copilotkit+runtime@1.3.6_class-validator@0.14.1_ignore@5.3.2\node_modules\@copilotkit\runtime
```

**Comment by ajinkyaT** [comment]
Hi, I updated to the latest packages but still getting the same error.

**Comment by NathanTarbert** [comment]
Hi @ajinkyaT, thanks for the heads up. 

I'm looking into this promptly

**Comment by NathanTarbert** [comment]
@ajinkyaT & @salman-khandu, please take a look at the bottom of the [Canvas Research demo README](https://github.com/CopilotKit/CopilotKit/tree/main/examples/coagents-research-canvas#troubleshooting) troubleshooting section. I initially had the same error but changed my 

```py
def main():
    """Run the uvicorn server."""
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run("research_canvas.demo:app", host="localhost", port=port)
    ``` 
    in `/agent/research_canvas/demo.py` and it worked. 
    This is not ideal if you are deployed or in production but please try one of the suggestions listed and let me know if it works for you.

**Comment by ajinkyaT** [comment]
@NathanTarbert No luck, I am trying with, [Human in the loop, demo](https://github.com/CopilotKit/CopilotKit/tree/main/examples/coagents-wait-user-input) 
This is my copilotkit versions:
@copilotkit/react-ui 1.3.15
├── @copilotkit/react-core 1.3.15
├── @copilotkit/runtime-client-gql 1.3.15
├── @copilotkit/shared 1.3.15

**Comment by ajinkyaT** [comment]
> @NathanTarbert No luck, I am trying with, [Human in the loop, demo](https://github.com/CopilotKit/CopilotKit/tree/main/examples/coagents-wait-user-input) This is my copilotkit versions: @copilotkit/react-ui 1.3.15 ├── @copilotkit/react-core 1.3.15 ├── @copilotkit/runtime-client-gql 1.3.15 ├── @copilotkit/shared 1.3.15

Okay I solved the problem for me, your documentation needs some serious work to keep it updated. 
in ui part change below in api/copilotkit/route.ts

```
const runtime = new CopilotRuntime({
    remoteActions: [
        {
            url: "http://localhost:8000/copilotkit",
        },
    ],
});
```

notice 'remoteActions' instead of 'remoteEndpoints' which is mentioned in the docs, as well as examples. Works for above mentioned versions which are tagged as latest as of now on https://www.npmjs.com/package/@copilotkit/react-core

**Comment by NathanTarbert** [comment]
Hi @ajinkyaT, we are looking into this, thank you!
