### ISSUE TITLE
🐛 Bug: Error adding actions inside CopilotRuntime

### ISSUE THREAD

**Issue by troyxdp** [CopilotKit/CopilotKit#941]
### ♻️ Reproduction Steps

I have the following code:
```
import { createServer } from 'node:http';
import {
  CopilotRuntime,
//   OpenAIAdapter,
  copilotRuntimeNodeHttpEndpoint,
  OpenAIAssistantAdapter
} from '@copilotkit/runtime';
import OpenAI from 'openai';
 
const openai = new OpenAI({ apiKey: "xxx" });
// const serviceAdapter = new OpenAIAdapter({ openai });
const serviceAdapter = new OpenAIAssistantAdapter({
    openai,
    assistantId: 'xxx',
    codeInterpreterEnabled: false,
    fileSearchEnabled: true
})

 
const server = createServer((req, res) => {
  const runtime = new CopilotRuntime({
    actions: ({properties, url}) => {
      return [
        {
          name: "fetchNameForUserId",
          description: "Fetches user name from the database for a given ID.",
          parameters: [
            {
              name: "userId",
              type: "string",
              description: "The ID of the user to fetch data for.",
              required: true,
            },
          ],
          handler: async ({userId}: {userId: string}) => {
            // do something with the userId
            // return the user data
            return {
              name: "Darth Doe",
            };
          },
        },
      ]
    }
  });

  const handler = copilotRuntimeNodeHttpEndpoint({
    endpoint: '/copilotkit',
    runtime,
    serviceAdapter,
  });
 
  return handler(req, res);
});
 
server.listen(4000, () => {
  console.log('Listening at http://localhost:4000/copilotkit');
});
```
which is the same as is indicated in the documents. However, it gives me an error saying that the constructor for CopilotRuntime expects 0 arguments but I'm giving it 1. It also gives errors regarding the types of "properties" and "url". The logs are included in this issue. 

I am running Node v22.11.0, and I am using the following command to run the file:
`ts-node src/server.ts`
Any assistant would be much appreciated. 

### ✅ Expected Behavior

I expect it to run

### ❌ Actual Behavior

It doesn't run

### 𝌚 CopilotKit Version

```shell
├── @copilotkit/react-core@1.3.15
├── @copilotkit/react-ui@1.3.15
├── @copilotkit/runtime@1.3.15
```

### 📄 Logs (Optional)

```shell
TSError: ⨯ Unable to compile TypeScript:
src/server.ts:21:38 - error TS2554: Expected 0 arguments, but got 1.

 21   const runtime = new CopilotRuntime({
                                         ~
 22     actions: ({}) => {
    ~~~~~~~~~~~~~~~~~~~~~~
... 
 44     }
    ~~~~~
 45   });
    ~~~

    at createTSError (/home/refraime/.nvm/versions/node/v22.11.0/lib/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/refraime/.nvm/versions/node/v22.11.0/lib/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/refraime/.nvm/versions/node/v22.11.0/lib/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/refraime/.nvm/versions/node/v22.11.0/lib/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/refraime/.nvm/versions/node/v22.11.0/lib/node_modules/ts-node/src/index.ts:1617:30)
    at node:internal/modules/cjs/loader:1689:10
    at Object.require.extensions.<computed> [as .ts] (/home/refraime/.nvm/versions/node/v22.11.0/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14) {
  diagnosticCodes: [ 2554 ]
}
```

**Comment by NathanTarbert** [comment]
Thanks for flagging this @troyxdp, we are looking into it and will get back to you.

**Comment by officialrobert** [comment]
Hey @troyxdp do you mind sharing your `tsconfig` and `package.json` file? Thanks! I tried replicating this bug in a Next.js setup, and it works fine even during build time. 


That said, with the release of `1.4.0` this error on your end could be fixed.

**Comment by tylerslaton** [comment]
Given that this issue is a bit stale I'm going to close this. Please re-open should you (or anyone else) see something like this.

**Comment by mymail4blogs** [comment]
i am still having that issue when integrating with Mastra
